---
title: "Linking evolutionary and ecological theory illuminates non-equilibrium biodiversity"
header-includes:
   - \usepackage{xr}
   - \externaldocument{EcoEvoNonStat_supp}
   - \usepackage{lineno}
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    number_sections: no
csl: mec.csl
bibliography: EcoEvoNonStat.bib
---


```{r setup, include = FALSE, message = FALSE, warning = FALSE, eval = FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE, message = FALSE,
                      warning = FALSE)

# function for cross-cache lazy loading
findChunk <- function(key, otherDoc) {
    f <- file.path(paste(otherDoc, 'cache', sep = '_'), 'latex')
    
    allChunk <- list.files(f, pattern = '.RData')
    
    thisChunk <- gsub('\\.RData', '', grep(paste0(key, '_'), allChunk, value = TRUE))
    thisChunk <- file.path(f, thisChunk)
    
    return(thisChunk)
}

# function for cross-doc figure referencing
refOtherFig <- function(x, otherDoc, prefix = '') {
    
}

# load packages
pkgs <- readLines('RarePlusComMinus_supp_cache/latex/__packages')
for(p in pkgs) library(p, character.only = TRUE)

# load plotting defaults
lazyLoad(findChunk('plot_defaults', 'RarePlusComMinus_supp'))
figW <- figH <- 3.5
knitr::opts_chunk$set(fig.width = figW, fig.height = figH, fig.align = 'center')

# load threading defaults
lazyLoad(findChunk('threading', 'RarePlusComMinus_supp'))
```

\linenumbers

> ### Abstract

> Whether or not biodiversity dynamics tend toward stable equilibria remains an unsolved question in ecology and evolution with important implications for our understanding of diversity and its conservation. Phylo/population genetic models and macroecological theory represent two primary lenses through which we view biodiversity. While phylo/population genetics provide an averaged view of changes in demography and diversity over timescales of generations to geological epochs, macroecology provides an ahistorical description of commonness and rarity across contemporary co-occurring species. Our goal is leverage advances in community-wide high throughput sequencing technology, specifically metabarcoding, to combine evolutionary and macroecological approaches to gain novel insights into the non-equilibrium nature of biodiversity.  We help guide near future research with a call for bioinformatic advances and an outline of quantitative predictions made possible by our approach.
\newline
\newline


# Non-equilibrium, inference, and theory in ecology and evolution

The idea of an ecological and evolutionary equilibrium has pervaded
studies of biodiversity from geological to ecological, and from global
to local [@sepkoski1984; @rabosky2009; @hubbell2001; @harte2011; @chesson2000; @tilman2004]. The consequences of non-equilibrium
dynamics for biodiversity are not well understood and the need to
understand them is critical with anthropogenic pressures forcing
biodiversity into states of rapid transition
[@blonder2015]. Non-equilibrial processes could profoundly inform
conservation in ways only just beginning to be explored
[@wallington2005].

Biodiversity theories based on assumptions of equilibrium, both
mechanistic [@hubbell2001; @chesson2000; @tilman2004] and
statistical **(see the Glossary)** [@harte2011; @pueyo2007]
have found success in predicting ahistorical patterns of diversity
such as the species abundance distribution [@white2012; @hubbell2001; @harte2011] and the species area relationship
[@hubbell2001; @harte2011]. These theories assume a
macroscopic equilibrium in terms of these coarse-grained metrics, as
opposed to focusing on details of species identity (such as
in @blonder2015), although macroscopic and microscopic approaches
are not mutually exclusive.  Nonetheless, the equilibrium assumed by
these theories is not realistic [@ricklefs2006], and many
processes, equilibrial or otherwise, can generate the same
macroscopic, ahistorical predictions [@mcgill2007].

Tests of equilibrial ecological theory alone will not allow us to
identify systems out of equilibrium, nor permit us to pinpoint the
mechanistic causes of any non-equilibrial processes. The dynamic
natures of evolutionary innovation and landscape change suggest that
ecological theory could be greatly enriched by synthesizing its
insights with inference from population genetic theory that explicitly
accounts for history. This would remedy two shortfalls of equilibrial
theory: 1) if theory fits observed ahistorical patterns but the
implicit dynamical assumptions were wrong, we would make the wrong
conclusion about the equilibrium of the system; 2) if theories do not
fit the data we cannot know why unless we have a perspective on the
temporal dynamics underlying those data.

No efforts to date have tackled these challenges. We propose that
combining insights from ecological theory and inference of
evolutionary and demographic change from genetic data will allow us to
understand and predict the consequences of non-equilibrial processes
in governing the current and future states of ecological
assemblages. The advent of high throughput sequencing-enabled metabarcoding has made unprecedented data available about the biodiversity of lineages from microbes to arthropods [@taberlet2012; @gibson2014; @shokralla2015; @ji2013; @zhou2013; @bohmann2014; @linard2015; @leray2015; @dodsworth2015; @liu2016; @venkataraman2015]. These metabarcoding data have great potential to yield synthetic insight across ecology and evolution.  However, to draw such insights we need a new tool set of bioinformatic methods **(Box box:dry)** and meaningful predictions **(section ref sec:pred )** grounded in theory to make use of those data. We present the foundation of this methedological tool set here.


# Ecological theories and non-equilibrium

Neutral and statistical theories in ecology focus on macroscopic
patterns, and equilibrium is presumed to be relevant to those
patterns. Our goal throughout is not to validate neutral or statistical
theories---quite the opposite, we propose new data dimensions, namely
genetics, to help better test alternative hypotheses against these
null theories, thereby gaining insight into what non-neutral and
non-statistical mechanisms are at play in systems of interest.

<!-- what to do about non-neutral models? here (until next comment tag) we say they drive non-equlibrium, below we say they're consistent with stat mech at large scale -->
Non-neutral and non-statistical models (e.g., @tilman2004; @chesson2000) also invoke ideas of equilibrium in their
derivation. However, these equilibria focus on the micro-scale details
of species interactions, which could in fact lead to instability and non-equilibrium at larger scales (cite: romGEB, critical transition in food web stuff from Beth, random matrix theory). Thus, detailed species interactions could in fact be drivers of non-equilibrium and thus
interesting hypotheses to test as alternatives to neutral/statistical models.
<!-- end of comment section  -->

To use neutral/statistical theories as null models, we need a robust measure of
goodness of fit. The emerging consensus is that likelihood-based test
statistics should be preferred [@baldridge2016]. The "exact
test" of @etienne2007 has been extended by @meteR into a simple z-score which can parsimoniously
describe the goodness of fit between theory and pattern.  We advocate
its use in our proposed framework.

<!-- consider moving below sections (down to comment tag 'theory_background') to earlier in intro (as a way to avoid using boxes/glossary all together) -->

The unified neutral theory of biodiversity (UNTB) [@hubbell2001] is a
useful null because it assumes that one mechanism---demographic
drift---drives community assembly.  Equilibrium occurs when
homogeneous stochastic processes of birth, death, speciation and
immigration have reached stationarity. Thus neutrality in ecology is
analogous to neutral drift in population genetics [@hubbell2001] (also cite molecular neutral theory).

Rather than assuming any one mechanism dominates the assembly of
populations into a community, statistical theories assume all
mechanisms could be valid, but their unique influences have been lost to
the enormity of the system and thus the outcome of assembly is a
community in statistical equilibrium [@harte2011; pueyo2007]. The
mechanistic agnosticism is what makes statistical theories useful
nulls. These statistical theories are also consistent with niche-based
equilibria [@pueyo2007; @neill2009] if the complicated, individual or
population level models with many mechanistic drivers were to be
upscaled to entire communities.

The maximum entropy theory of ecology (METE) [@harte2011]
derives its predictions by condensing the many bits of mechanistic
information down into ecological state variables and then
mathematically maximizing information entropy conditional on those
state variables. METE can predict multiple ahistorical patterns,
including distributions of species abundance, body size, spatial
aggregation, and trophic links [@harte2011; @rominger2015; @meteR], making
for a stronger null theory [@mcgill2003]. However, multiple
dynamics can still map to this handful of metrics [@mcgill2007]
and while extensive testing often supports METE's predictions
[@harte2011; white2012; xiao2015] at single snapshots in time,
METE fails to match observed patterns in disturbed and rapidly
evolving communities [@rominger2015; harte2011]. Just like deviations from UNTB, we cannot know the cause of these departures from theoretical predictions without adding tests of theories and metrics that capture temporal dynamics.

<!-- end of comment section 'theory_background'-->


# Inferring non-equilibrium dynamics

Unlocking insight into the dynamics underlying community assembly is
key to overcoming the limitations of analyzing ahistorical patterns
with equilibrial theory. While the fossil record could be used for
this task, it has limited temporal, spatial, and taxonomic
resolution. Here we instead focus on population/phylogenetic insights
into rates of change of populations and species because while there are real limitations in the accuracy and resolution of temporal dynamics with population genetic (cite) and phylogenetic (cite) methods, they can, in principle, be applied to any extant group. Additionally, despite limitations in resolving detailed temporal dynamics, robust metrics of deviation from simple, stationary birth-death and/or speciation-extinction processes have been well-established and widely used for population genetic and phylogenetic data (cite about Tajima D, gamma stats, etc). 


<!-- Do we need this? -->

<!-- Bridging ecological theory -->
<!-- with models from population/phylogenetics has great potential -->
<!-- \citep{webb2002, lavergne2010, mcgaughran2015, laroche2015, -->
<!--   papadopoulou2011, dexter2012} that has yet to be fully realized. How -->
<!-- we can best link the inferences of change through time from -->
<!-- population/phylogenetics with inferences from macroecology is governed -->
<!-- by what insights we can gain from genetic perspectives on demography -->
<!-- and diversification. -->

<!-- Coalescent theory \citep{kingman1982stochasti, rosenberg2002} is one -->
<!-- of the fundamental population genetics tools allowing model-based -->
<!-- estimation of complex historical processes. These include population -->
<!-- size fluctuations \citep{kuhner1998}, divergence and/or colonization -->
<!-- times \citep{charlesworth2010, edwards2000}, migration rates -->
<!-- \citep{wakeley2008}, selection \citep{kern2016}, and complex patterns -->
<!-- of historical population structure \citep{prado-martinez2013} and gene -->
<!-- flow \citep{beerli2001, hey2004}. This approach can also be put in a -->
<!-- multi-species, community context via hierarchical demographic models -->
<!-- \citep{xue2015, hickerson2006, carstens2016, chan2014}, even when only -->
<!-- small numbers of genetic loci are sampled from populations -->
<!-- \citep{drummond2005}. -->

<!-- These modeled demographic deviations from neutral demographic -->
<!-- equilibrium can also be condensed into multi-species summary -->
<!-- statistics. For example, Tajima's D, which measures the strength of -->
<!-- non-equilibrium demography in a single population \citep[see Glossary -->
<!-- for more details;][]{tajima1989, jensen2005, schrider2016, -->
<!--   stephan2016}, could be averaged over all populations in a sample. -->


# Current efforts to integrate evolution into ecological theory

While quantitatively integrating theory from ecology, population
genetics, and phylogenetics has not yet been achieved, existing
efforts to synthesize perspectives from evolution and ecology point
toward promising directions despite being hindered by one or more
general issues: 1) lack of a solid theoretical foundation, 2)
inability to distinguish multiple competing alternative hypotheses, 3)
lack of comprehensive genetic/genomic data, and 4) lack of
bioinformatic approaches to resolve species and their abundances with high throughput sequencing data.

Phylogenetic information has been incorporated into studies of the UNTB
to better understand its ultimate equilibrium [@jabot2009; @burbrink2015].  However, phylogenetic reasoning also points out the
flaws in the UNTB's presumed equilibrium [@ricklefs2006].
Attempts to correct the assumed dynamics of UNTB through "protracted
speciation" [@rosindell2010] are promising, and while their
implications for diversification have been considered
[@etienne2011], these predictions have not been integrated with
demographic and phylogeographic approaches
(e.g., [@charlesworth2010; @edwards2000; @prado-martinez2013])
that have the potential to validate or falsify presumed mechanisms of
lineage divergence.  Such demographic studies, particularly
phylogeographic investigations of past climate change, have highlighted the non-equilibrium
responses of specific groups to perturbations [@smith2012; @hickerson2005], but no attempt has been made to scale up these
observations to implications at the level of entire communities. The
recent growth in joint studies of genetic and species diversity
[@vellend2005amnat; @papadopoulou2011] have been useful in linking
population genetics with ecological and biogeographic concepts. 

<!-- I think I want to say something else about correlative gen div and species div -->
<!-- maybe something about how they're not based in theory? have no theoretical basline? -->

<!-- maybe we don't need this since MESS is already a thing now -->
<!-- These correlative studies could be bolstered by developing full joint models -->
<!-- that link community assembly, historical demography and -->
<!-- coalescent-based population genetics (cite MESS of course). -->

Studies have also used chronosequences or the fossil record in
combination with neutral and/or statistical theory to investigate
changes over geologic time in community assembly mechanisms
[@wagner2006; @rominger2015]. While these
studies have documented interesting shifts in assembly mechanisms,
including departures from equilibrium likely resulting from
evolutionary innovations, understanding exactly how the evolution of
innovation is responsible for these departures cannot be achieved
without more concerted integration with insights from evolutionary theory.


<!-- This section (below) seems pretty redundant and also builds up MESS (option 2) but MESS  -->
<!-- is already a thing now. Maybe we should scrap most of this section -->

<!-- Here's what I think we should do: -->
<!-- - incorperate the many-to-on mapping above (it's already pretty much there) -->
<!-- - use the description of "Option 1" to write a "here we do" statement -->
<!-- - borrow *some* content from the "What we gain from this framework" section to embelish the "here we do" statment -->

<!-- # What is needed now -->


<!-- A key limitation to using ahistorical theory to infer dynamic -->
<!-- mechanisms is that multiple mechanisms, from simple and equilibrial to -->
<!-- complex, can map onto the same ahistorical pattern -->
<!-- [@engen1996lnorm; @mcgill2003]. This means that even when a theory -->
<!-- describes the data well, we do not really know the dynamics that led -->
<!-- to that good fit [@ricklefs2006]. -->

<!-- Quantitatively integrating the dynamics inferred from population and -->
<!-- phylogenetic approaches with ahistorical, equilibrial ecological -->
<!-- theory can break this many-to-one mapping of mechanism onto prediction -->
<!-- and contextualize whether a match between ahistorical pattern and -->
<!-- theory truly results form equilibrial dynamics or only falsely -->
<!-- appears to. There are two complementary approaches to achieve this -->
<!-- integration (both discussed further in **Box ref box:dry**): -->

<!-- - Option 1: using dynamics from genetic inference to predict and -->
<!--   understand deviations from ahistorical theories. This amounts to -->
<!--   separately fitting ahistorical theory to typical macroecological -->
<!--   data, while also fitting population genetic and/or phylogenetic -->
<!--   models to genetic data captured for the entire community. Doing so -->
<!--   requires substantial bioinformatic advances that would allow the -->
<!--   joint capture of genetic or genomic data from entire community -->
<!--   samples using high throughput sequencing, while also estimating accurate abundances from -->
<!--   high throughput sequencing output. Separating model fitting avoids assumptions about how -->
<!--   macroecological quantities like abundance scale to evolutionary -->
<!--   metrics like effective population size; however, this approach does -->
<!--   not facilitate the elegance of model comparison as does joint modeling. -->
<!-- - Option 2: building off existing theories, develop new joint -->
<!--   models that simultaneously predict macroecological and population -->
<!--   genetic patterns. This amounts to building hierarchical models that -->
<!--   take genetic data as input and integrate over all possible community -->
<!--   states that could lead to these genetic data given a model of -->
<!--   community assembly and a model of population coalescence. This -->
<!--   approach requires making assumptions about how abundances scale to -->
<!--   effective population sizes, but is better suited for comparing -->
<!--   competing joint models of evolutionary history and assembly. -->


<!-- \subsection{What we gain from this framework} -->

<!-- Using our proposed framework, we can finally understand why -->
<!-- ahistorical theories fail when they do---is it because of rapid -->
<!-- population change, or evolution/long-distance dispersal of novel -->
<!-- ecological strategies? We could predict whether a system that obeys -->
<!-- the ahistorical predictions of equilibrial ecological theory is in -->
<!-- fact undergoing major non-equilibrial evolution. We could better -->
<!-- understand and forecast how/if systems out of equilibrium are likely -->
<!-- to relax back to equilibrial patterns. With such a framework we could -->
<!-- even flip the direction of causal inference and understand ecological -->
<!-- drivers of diversification dynamics. This last point bears directly on -->
<!-- long-standing debates about the importance of competitive limits on -->
<!-- diversification \citep{rabosky2009, harmon2015amNat}. Conclusions about -->
<!-- phylogenetic patterns (e.g. diversification slowdowns) would be more -->
<!-- believable and robust if combined with population genetic inference -->
<!-- (e.g. declining populations) and community patterns (e.g.  deviation -->
<!-- from equilibrium). -->


## Data and Code Availability

All data and code needed to reproduce the results of this manuscript are available at https://github.com/ajrominger/EcoEvoNonStat and a detailed description of the analytical approach is available in the supplement.


\clearpage

# References

