---
title: "EENS sections"
author: "RMD"
date: "2022-11-16"
output:
    pdf_document:
        toc: true
---

<!-- The topic sentences in the outline could make for a reasonable abstract/introduction. Using them here as scaffolding for individual sections, then will re-synthesize at the end. -->

# Linking null models in evolution and ecology with next generation sequencing data to illuminate non-equilibrium dynamics of biodiversity

<!-- @isaac, andy is NGS vs high-throughput more inclusive? -->



\newpage

##	As biologists, we are tasked with understanding and predicting how ecological/evolutionary systems change over time, especially in an era of dramatic changes to biodiversity.

<!-- The consequences of non-equilibrium dynamics for biodiversity are not well understood and the need to understand them is critical with anthropogenic pressures forcing biodiversity into states of rapid transition (Blonder et al., 2015). Non-equilibrial processes could profoundly inform conservation in ways only just beginning to be explored (Wallington et al., 2005).-->

Particularly in the current era of dramatic and often unprecedented disturbances to ecological and evolutionary processes, one of the key objectives for biodiversity scientists is to understand and predict how eco-evolutionary systems respond to perturbations. <!-- revisit this after the rest is done because there are many directions this para. can go and it just needs to plug in to *this* ms -->


\newpage

<!--A.	equilibrium Equilibrium is often reserved for systems in thermodynamic equilibrium— which all life violates. By “biodiversity equilibrium” we make an analogy to thermodynamics and say that biodiversity is in equilibrium if its marcrosopic state (e.g. richness of species abundance distribution, but not necessarily specific species compositions) is steady, and across arbitrary subsystems, the same steady state applies.
B.	statistical equilibrium In the context of biodiversity, a description of a steady state arrived at not by the force of one or a few deterministic mechanisms but by the stationary, statistical behavior of very large collections of mechanistic drivers acting on large assemblages of organisms.
C.	Neutral and statistical theories in ecology focus on macroscopic patterns, and equilibrium is presumed to be relevant to those patterns. Our goal throughout is not to validate neutral or statistical theories—quite the opposite, we propose new data dimensions, namely genetics, to help better test alternative hypotheses against these null theories, thereby gaining insight into what non-neutral and non-statistical mechanisms are at play in systems of interest.
D.	The unified neutral theory of biodiversity (UNTB; (Hubbell, 2001)) is a useful null because it assumes that one mechanism—demographic drift—drives community assembly. Equilibrium occurs when homogeneous stochastic processes of birth, death, speciation and immigration have reached stationarity. Thus neutrality in ecology is analogous to neutral drift in population genetics (Hubbell, 2001).
E.	Rather than assuming any one mechanism dominates the assembly of populations into a community, statistical theories assume all mechanisms could be valid, but their unique influences have been lost to the enormity of the system and thus the outcome of assembly is a community in statistical equilibrium (Harte, 2011; Pueyo et al., 2007). The mechanistic agnosticism is what makes statistical theories useful nulls. These statistical theories are also consistent with niche-based equilibria (Neill et al., 2009; Pueyo et al., 2007) if the complicated, individual or population level models with many mechanistic drivers were to be upscaled to entire communities.
-->

<!--

How do we get to

* focus on macroscopic properties
* macroscopic properties assumed to converge to some form of _statistical_ equilibrium
* _deviations_ from statistical equilibrium may be symptomatic of perturbations that temporarily overwhelm the enormity-of-the-system


-->

### Statistical null models for complex eco-evolutionary systems
<!-- we can have some feelings about "complex systems" :sparkles: but I like it here - targeting a non-CS audience who needs to be sold on statistical nulls -->

Eco-evolutionary systems are intrinsically complex systems, in the sense that they are made up of numerous components (genes, individuals, species) interacting via a multitude of interrelated, often stochastic and/or nonlinear, pathways. Rather than attempting to model and predict the behavior of these systems in exacting mechanistic detail (e.g. the exact population dynamics of individual species), it is therefore often pragmatic to focus instead on the emergent, macroscopic properties of these systems (such as the distribution of abundance among all species <!-- or popgen equivalent-->).

The macroscopic focus is especially promising for understanding how disturbances affect eco-evolutionary systems. Macroscopic properties tend to be relatively insensitive to minor changes at lower levels of organization, due in part to the phenomenon of _staistical equilibrium_. In complex systems in general, when a large number of random processes combine to generate a phenomenon (such as the shape of the species abundance distribution), the fine-scale details of these processes can smooth or cancel each other out and result in consistent, predictable macroscopic outcomes that converge with the outcomes that emerge from simple null models. Through statistical averaging, these macroscopic phenomena are relatively insensitive to subtle variations or perturbations at lower levels of organization. However, a sufficiently strong perturbation can temporarily overwhelm statistical equilbrium and produce macroscopic outcomes that deviate from the expectations of statistical null models. These deviations can be used to detect and diagnose strong perturbations operating in complex systems. This conceptual framework is the foundation of, for example, applications of the principle of maximum entropy in statistical mechanics.


Efforts to use deviations from statistical null theories in ecology and evolution have demonstrated that this is a useful approach. Rather than assuming any one mechanism dominates the assembly of populations into a community, these theories assume all mechanisms could be valid, but their unique influences have been lost to the enormity of the system and thus the outcome of assembly is a community in statistical equilibrium (Harte, 2011; Pueyo et al., 2007). The mechanistic agnosticism is what makes statistical theories useful nulls. These statistical theories are also consistent with niche-based equilibria (Neill et al., 2009; Pueyo et al., 2007) if the complicated, individual or population level models with many mechanistic drivers were to be upscaled to entire communities. In ecology, the Maximum Entropy Theory of Ecology (METE) has been shown to successfully predict the shape of numerous macroscopic distributions given only a restricted set of "state variables" (species richness, total abundance, and optionally total metabolic flux) and minimal assumptions about ecological process. In contrast, systems that have recently undergone major disturbances - such as forests that have been clear-cut, or oceanic island communities that have only recently emerged - deviate markedly from the statistical null expectations derived from METE. In population genetics, deviations from neutral genetic drift are routinely used to detect and diagnose disturbances such as population bottlenecks.

Historically, applications of statistical equilibrium in ecology and evolution have proceeded separately - i.e. the fields of macroecology () and population genetics <!-- surely there is a better term for neutral popgen? @isaac? --> - but integrating ecological and evolutionary statistical nulls can provide new insights not possible through focusing on either of these phenomena separately <!-- i hate it -->. While macroecology has revealed several ecological patterns that have provided useful insight into general processes and the importance of statistical nulls in ecology, it has become increasingly clear that the patterns traditionally entertained in macroecology do not, on their own, contain sufficient information to distinguish among competing hypotheses. In particular, macroecology has largely adopted a time-averaged perspective that is not capable of accounting for temporal or historical dynamics. Incorporating population genetics with macroecology would provide additional data dimensions for statistical inference, and would provide a *historical* perspective that is critical for understanding how past disturbances influence contemporary patterns. On the other hand, ecological population genetics has historically focused on the dynamics of a single focal species or population, and only indirectly incorporated larger scale processes (but see ...).  <!--I am sure this is wrong, @isaac or @andy help!!!-->  

So far, progress towards integrating statistical null models in macroecology with community genetics has shown promise (...) but has been largely constrained by the lack of a unified theoretical framework for population genetic and macroecological patterns, on one hand, and the lack of empirical data incorporating both organismal abundance and community genetic data, on the other. In the absence of a quantitative framework linking macroecological and population genetic dynamics, the field has instead used retroactive modifications to macroecological models () or explored qualitative hypotheses about the co-variation of, for example, species and genetic diversity (). However, recent advances in simulation modeling of _joint_ ecological and evolutionary processes open up new ground for developing and testing rigorous predictions for how various types of equilibrial and non-equilibrial dynamics are expected to manifest at _both_ organismal and genetic levels (...). Simultaneously, next-generation sequencing technologies will soon make it economical and efficient to collect community-wide genetic data to complement organismal abundance data. The data produced via these methods are naturally suited to testing theoretical predictions for joint genetic and community dynamics, and can provide inferential leverage for diagnosing present and past non-equilibral processes not discernible using present approaches.

Here, we illustrate how statistical null models of joint population genetic and ecological dynamics, coupled with community genetic sequencing data, can illuminate historical and contemporary trajectories of eco-evolutionary systems. We present a theoretical framework for interpreting deviations from statistical equilibrium at ecological and/or population genetic levels, and use simulation models to demonstrate how different scenarios of non-equilibrial dynamics fit into this framework. We demonstrate using this framework with empirical data on species' abundances and genetic diversity, and illustrate a prospective bioinformatic pipeline for applying this framework to next-generation sequencing data. We hope that these theoretical and methodological advances will inspire future steps integrating community genetic sequencing with statistical null models to understand and predict trajectories of ecological and evolutionary change in the Anthropocene. 
